# Site settings
title: Grouplet Playbook
email: michael.bland@gsa.gov
description: >
  A set of principles, practices, idioms, and strategies pertaining to
  the organization of ad-hoc working groups, aka "grouplets".
baseurl: "/grouplet-playbook"
url: "http://18f.gsa.gov"
github_username:  mbland

# Build settings
markdown: redcarpet
exclude:
- README.md
- LICENSE.md
- CONTRIBUTING.md
- deploy
- vendor
- go

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "default"
      edit_info:
        repo: 18F/grouplet-playbook
        branch: master
